# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Luis Mendoza | Front-end developer and wedding photographer
email: luis@mendoza.io
description: > # this means to ignore newlines until "baseurl:"
  Based in Mexico City, Luis Mendoza (@luismendozamx) works
  on front-end and full-stack web development with Ember.js, Angular,
  and Rails.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.mendoza.io" # the base hostname & protocol for your site
twitter_username: luismendozamx
github_username:  luismendozamx

# Build settings
markdown: kramdown
exclude: ['Gemfile', 'Gemfile.lock']
